package cn.succy.jfinal.common.model;

import cn.succy.jfinal.common.model.base.BaseBlog;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog> {
	public static final Blog dao = new Blog().dao();

	public Page<Blog> paginate(int pageNum, int pageSize) {
		return paginate(pageNum, pageSize, "select *","from blog order by id asc");
	}
}
